[package]
name = "nightfall"
version = "0.1.0"
edition = "2024"
author="Mofe Bankole"
email="bankoladedotun16@gmail.com"
github=""

[dependencies]
actix = "0.13.5"
anyhow = "1.0.100"
axum = "0.8.6"
chrono = "0.4.42"
orchard = "0.11.0"
dotenv = "0.15.0"
pczt = "=0.3.0"
serde = "1.0.228"
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
uuid = "1.18.1"
zcash_client_backend = "0.21.0"
reqwest = { version = "0.12", features = ["json"] }
hex = "0.4"
zcash_primitives = "0.26.1"
zcash_proofs = "0.26.1"
bcrypt = "0.17.1"
jsonwebtoken = { version = "10.2.0" , features = ["rust_crypto"] }
