[package]
name = "nightfall"
version = "0.1.0"
edition = "2024"
author="Mofe Bankole"
email="bankoladedotun16@gmail.com"
github=""

[dependencies]
actix = "0.13.5"
anyhow = "1.0.100"
axum = "0.8.6"
orchard = "0.11.0"
dotenv = "0.15.0"
pczt = "=0.3.0"
serde = "1.0.228"
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono"] }
tokio = { version = "1.48.0", features = ["full"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
tracing-subscriber = "0.3.20"
reqwest = { version = "0.12", features = ["json"] }
hex = "0.4"
zcash_primitives = "0.26.1"
zcash_proofs = { version = "0.26", features = ["bundled-prover"] }
zcash_script = "0.4"
secp256k1 = { version = "0.29", features = ["serde"] }
zcash_transparent = "0.6.1"
zcash_encoding = "0.3.0"
bcrypt = "0.17.1"
jsonwebtoken = { version = "10.2.0" , features = ["rust_crypto"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
chrono = { version = "0.4.41", features = ["serde"] }
zip32 = "0.2"
zip321 = "0.6"
bip32 = { version = "=0.6.0-pre.1", default-features = false, features = ["secp256k1-ffi"] }
zcash_client_backend = { version = "0.21", features = ["lightwalletd-tonic-tls-webpki-roots", "orchard", "pczt"] }
zcash_keys = { version = "0.11", features = ["orchard"] }
